insert into teacher(id,first_name,last_name) values(11, 'teacher', 'one')
insert into teacher(id,first_name,last_name) values(12, 'teacher', 'two')
insert into teacher(id,first_name,last_name) values(13, 'teacher', 'three')
insert into teacher(id,first_name,last_name) values(14, 'teacher', 'four')
insert into teacher(id,first_name,last_name) values(15, 'teacher', 'five')